import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Container from "./components/Container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Product Feedback App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#F7F8FD]`}
      >
        <div className="lg:grid lg:grid-cols-4 lg:container lg:mx-auto lg:px-5">
          {children}
        </div>
      </body>
    </html>
  );
}
