import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "./navigationbar/Navbar";
import Sort from "./components/Sort";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Product Feedback App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#F7F8FD]`}
      >
        <NavBar />
        <Sort />
        {children}
      </body>
    </html>
  );
}
